### ISSUE TITLE
License

### ISSUE THREAD

**Issue by pchaigno** [peta/turtle.tmbundle#11]
We would like to use your bundle at github/linguist to highlight SPARQL and Turtle code on GitHub but I don't know what licensing terms you're distributing it under.
Any chance you could pick one from here: http://choosealicense.com?

**Comment by pchaigno** [comment]
@peta Did you get a chance to look into it since last time? (We have to wait for the license file to merge github/linguist#1841 :-)

**Comment by peta** [comment]
@pchaigno Yes, I added a license file right now. :)

**Comment by pchaigno** [comment]
@peta Thanks!
